# Import ChatOpenAI to use OpenAI's chat-based language models
from langchain_openai import ChatOpenAI

# Import load_dotenv to load environment variables from the .env file
from dotenv import load_dotenv


# Load the API key and other environment variables from the .env file
load_dotenv()


# Create the OpenAI chat model
# model='gpt-4' specifies which model to use
# temperature=1.5 controls the creativity/randomness of the response
model = ChatOpenAI(
    model='gpt-4',
    temperature=1.5
)


# Send a prompt to the model and get the response
result = model.invoke(
    "Write a 5 line poem on cricket"
)


# Print only the actual text/content generated by the AI
print(result.content)